### ISSUE TITLE
Got this: 'charmap' codec can't encode character '\U0001f44b' in position 4: character maps to <undefined>

### ISSUE THREAD

**Issue by ke1ne** [NeuralRealm/StableFusion#2]
Hi, I've tried to run on Windows 11 and got this error message:

`'charmap' codec can't encode character '\U0001f44b' in position 4: character maps to <undefined>`

Tried to install from source and from pip.

**Comment by ke1ne** [comment]
> Use a virtual environment for it

I'm already using local venv.

> If the problem doesn't solve you can use encoding='utf-8' on the text file.

Sorry, which file did you mean?

**Comment by everydaycodings** [comment]
model_list.txt file
today I will run the on my windows virtual machine if the error occurs then I will make some changes in the code.
and please could you give me your error log so that I can understand where was the exact error.

**Comment by ke1ne** [comment]
Thanks. I re-saved the StableFusion\stablefusion\model_list.txt file with UTF-8, got the same message.

Here is a full log:

![image](https://user-images.githubusercontent.com/8934421/223385566-48ce0712-15bb-43fc-aa54-ccc60de65958.png)

**Comment by everydaycodings** [comment]
I have updated the repo with some possible fixes use the git clone method to reinstall the stablefusion and please remove the pip version of stablefusion.

**Comment by everydaycodings** [comment]
> I have updated the repo with some possible fixes using the git clone method to reinstall the stablefusion and please remove the pip version of stablefusion.

and please tell us if this solves the problem, if not then have patients use it in google collab we will come up with the fix soon.

**Comment by ke1ne** [comment]
Reinstalled from scratch:
```
git clone https://github.com/NeuralRealm/StableFusion
cd StableFusion
python -m venv venv
.\venv\Scripts\activate
pip install -e .
stablefusion app
```
Result:
`2023-03-07 15:14:46.619 'charmap' codec can't encode character '\U0001f44b' in position 4: character maps to <undefined>`

Sure, no rush. Just playing around, excited to try new tool and maybe even stick with it. Thank you!
